// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package sls

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogContent struct {
	Key                  *string  `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogContent) Reset()         { *m = LogContent{} }
func (m *LogContent) String() string { return proto.CompactTextString(m) }
func (*LogContent) ProtoMessage()    {}
func (*LogContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *LogContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogContent.Unmarshal(m, b)
}
func (m *LogContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogContent.Marshal(b, m, deterministic)
}
func (m *LogContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogContent.Merge(m, src)
}
func (m *LogContent) XXX_Size() int {
	return xxx_messageInfo_LogContent.Size(m)
}
func (m *LogContent) XXX_DiscardUnknown() {
	xxx_messageInfo_LogContent.DiscardUnknown(m)
}

var xxx_messageInfo_LogContent proto.InternalMessageInfo

func (m *LogContent) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *LogContent) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Log struct {
	Time                 *uint32       `protobuf:"varint,1,req,name=Time" json:"Time,omitempty"`
	Contents             []*LogContent `protobuf:"bytes,2,rep,name=Contents" json:"Contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Log) GetContents() []*LogContent {
	if m != nil {
		return m.Contents
	}
	return nil
}

type LogTag struct {
	Key                  *string  `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogTag) Reset()         { *m = LogTag{} }
func (m *LogTag) String() string { return proto.CompactTextString(m) }
func (*LogTag) ProtoMessage()    {}
func (*LogTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}

func (m *LogTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogTag.Unmarshal(m, b)
}
func (m *LogTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogTag.Marshal(b, m, deterministic)
}
func (m *LogTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogTag.Merge(m, src)
}
func (m *LogTag) XXX_Size() int {
	return xxx_messageInfo_LogTag.Size(m)
}
func (m *LogTag) XXX_DiscardUnknown() {
	xxx_messageInfo_LogTag.DiscardUnknown(m)
}

var xxx_messageInfo_LogTag proto.InternalMessageInfo

func (m *LogTag) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *LogTag) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type LogGroup struct {
	Logs                 []*Log    `protobuf:"bytes,1,rep,name=Logs" json:"Logs,omitempty"`
	Category             *string   `protobuf:"bytes,2,opt,name=Category" json:"Category,omitempty"`
	Topic                *string   `protobuf:"bytes,3,opt,name=Topic" json:"Topic,omitempty"`
	Source               *string   `protobuf:"bytes,4,opt,name=Source" json:"Source,omitempty"`
	MachineUUID          *string   `protobuf:"bytes,5,opt,name=MachineUUID" json:"MachineUUID,omitempty"`
	LogTags              []*LogTag `protobuf:"bytes,6,rep,name=LogTags" json:"LogTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogGroup) Reset()         { *m = LogGroup{} }
func (m *LogGroup) String() string { return proto.CompactTextString(m) }
func (*LogGroup) ProtoMessage()    {}
func (*LogGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3}
}

func (m *LogGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogGroup.Unmarshal(m, b)
}
func (m *LogGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogGroup.Marshal(b, m, deterministic)
}
func (m *LogGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogGroup.Merge(m, src)
}
func (m *LogGroup) XXX_Size() int {
	return xxx_messageInfo_LogGroup.Size(m)
}
func (m *LogGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_LogGroup.DiscardUnknown(m)
}

var xxx_messageInfo_LogGroup proto.InternalMessageInfo

func (m *LogGroup) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *LogGroup) GetCategory() string {
	if m != nil && m.Category != nil {
		return *m.Category
	}
	return ""
}

func (m *LogGroup) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *LogGroup) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *LogGroup) GetMachineUUID() string {
	if m != nil && m.MachineUUID != nil {
		return *m.MachineUUID
	}
	return ""
}

func (m *LogGroup) GetLogTags() []*LogTag {
	if m != nil {
		return m.LogTags
	}
	return nil
}

type SlsLogPackage struct {
	Data                 []byte   `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	UncompressSize       *int32   `protobuf:"varint,2,opt,name=uncompress_size,json=uncompressSize" json:"uncompress_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlsLogPackage) Reset()         { *m = SlsLogPackage{} }
func (m *SlsLogPackage) String() string { return proto.CompactTextString(m) }
func (*SlsLogPackage) ProtoMessage()    {}
func (*SlsLogPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{4}
}

func (m *SlsLogPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlsLogPackage.Unmarshal(m, b)
}
func (m *SlsLogPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlsLogPackage.Marshal(b, m, deterministic)
}
func (m *SlsLogPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlsLogPackage.Merge(m, src)
}
func (m *SlsLogPackage) XXX_Size() int {
	return xxx_messageInfo_SlsLogPackage.Size(m)
}
func (m *SlsLogPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_SlsLogPackage.DiscardUnknown(m)
}

var xxx_messageInfo_SlsLogPackage proto.InternalMessageInfo

func (m *SlsLogPackage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SlsLogPackage) GetUncompressSize() int32 {
	if m != nil && m.UncompressSize != nil {
		return *m.UncompressSize
	}
	return 0
}

type SlsLogPackageList struct {
	Packages             []*SlsLogPackage `protobuf:"bytes,1,rep,name=packages" json:"packages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SlsLogPackageList) Reset()         { *m = SlsLogPackageList{} }
func (m *SlsLogPackageList) String() string { return proto.CompactTextString(m) }
func (*SlsLogPackageList) ProtoMessage()    {}
func (*SlsLogPackageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{5}
}

func (m *SlsLogPackageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlsLogPackageList.Unmarshal(m, b)
}
func (m *SlsLogPackageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlsLogPackageList.Marshal(b, m, deterministic)
}
func (m *SlsLogPackageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlsLogPackageList.Merge(m, src)
}
func (m *SlsLogPackageList) XXX_Size() int {
	return xxx_messageInfo_SlsLogPackageList.Size(m)
}
func (m *SlsLogPackageList) XXX_DiscardUnknown() {
	xxx_messageInfo_SlsLogPackageList.DiscardUnknown(m)
}

var xxx_messageInfo_SlsLogPackageList proto.InternalMessageInfo

func (m *SlsLogPackageList) GetPackages() []*SlsLogPackage {
	if m != nil {
		return m.Packages
	}
	return nil
}

type LogGroupList struct {
	LogGroups            []*LogGroup `protobuf:"bytes,1,rep,name=LogGroups" json:"LogGroups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LogGroupList) Reset()         { *m = LogGroupList{} }
func (m *LogGroupList) String() string { return proto.CompactTextString(m) }
func (*LogGroupList) ProtoMessage()    {}
func (*LogGroupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{6}
}

func (m *LogGroupList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogGroupList.Unmarshal(m, b)
}
func (m *LogGroupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogGroupList.Marshal(b, m, deterministic)
}
func (m *LogGroupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogGroupList.Merge(m, src)
}
func (m *LogGroupList) XXX_Size() int {
	return xxx_messageInfo_LogGroupList.Size(m)
}
func (m *LogGroupList) XXX_DiscardUnknown() {
	xxx_messageInfo_LogGroupList.DiscardUnknown(m)
}

var xxx_messageInfo_LogGroupList proto.InternalMessageInfo

func (m *LogGroupList) GetLogGroups() []*LogGroup {
	if m != nil {
		return m.LogGroups
	}
	return nil
}

func init() {
	proto.RegisterType((*LogContent)(nil), "sls.LogContent")
	proto.RegisterType((*Log)(nil), "sls.Log")
	proto.RegisterType((*LogTag)(nil), "sls.LogTag")
	proto.RegisterType((*LogGroup)(nil), "sls.LogGroup")
	proto.RegisterType((*SlsLogPackage)(nil), "sls.SlsLogPackage")
	proto.RegisterType((*SlsLogPackageList)(nil), "sls.SlsLogPackageList")
	proto.RegisterType((*LogGroupList)(nil), "sls.LogGroupList")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886) }

var fileDescriptor_a153da538f858886 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0xc6, 0x49, 0xd2, 0xd6, 0xe4, 0xb4, 0xf5, 0xea, 0x20, 0x32, 0x5c, 0xa4, 0x84, 0x80, 0x58,
	0xb8, 0x98, 0x2b, 0xe2, 0xce, 0x9d, 0x15, 0x45, 0x1c, 0x41, 0xa6, 0xb9, 0x6e, 0x65, 0x1a, 0xc7,
	0x69, 0x30, 0xcd, 0x09, 0x99, 0x64, 0xd1, 0xbe, 0x9a, 0x2f, 0xe0, 0xd2, 0x47, 0x90, 0x3e, 0x89,
	0xf4, 0xa4, 0xd3, 0xda, 0x9d, 0xbb, 0xf3, 0xfb, 0xbe, 0xf3, 0x1f, 0xa2, 0x12, 0x4d, 0x5a, 0x37,
	0xd8, 0x22, 0x0b, 0x6c, 0x69, 0xaf, 0x9f, 0x9b, 0xa2, 0x5d, 0x77, 0xab, 0x34, 0xc7, 0xcd, 0xad,
	0x41, 0x83, 0xb7, 0xe4, 0xad, 0xba, 0xef, 0x44, 0x04, 0x14, 0xf5, 0x35, 0xc9, 0x2b, 0x00, 0x81,
	0x66, 0x81, 0x55, 0xab, 0xab, 0x96, 0x3d, 0x80, 0xe0, 0xa3, 0xde, 0x72, 0x2f, 0xf6, 0xe7, 0x91,
	0x3c, 0x84, 0xec, 0x11, 0x0c, 0xbf, 0xa8, 0xb2, 0xd3, 0xdc, 0x27, 0xad, 0x87, 0xe4, 0x1d, 0x04,
	0x02, 0x0d, 0x63, 0x30, 0xc8, 0x8a, 0x8d, 0xa6, 0xfc, 0xa9, 0xa4, 0x98, 0xdd, 0x40, 0x78, 0xec,
	0x66, 0xb9, 0x1f, 0x07, 0xf3, 0xf1, 0xcb, 0xab, 0xd4, 0x96, 0x36, 0x3d, 0x4f, 0x91, 0xa7, 0x84,
	0xe4, 0x05, 0x8c, 0x04, 0x9a, 0x4c, 0x99, 0xff, 0x9e, 0xfc, 0xd3, 0x83, 0x50, 0xa0, 0x79, 0xdf,
	0x60, 0x57, 0xb3, 0x27, 0x30, 0x10, 0x68, 0x2c, 0xf7, 0x68, 0x4e, 0xe8, 0xe6, 0x48, 0x52, 0xd9,
	0x35, 0x84, 0x0b, 0xd5, 0x6a, 0x83, 0xcd, 0x96, 0xfb, 0xb1, 0x37, 0x8f, 0xe4, 0x89, 0x0f, 0xcd,
	0x33, 0xac, 0x8b, 0x9c, 0x07, 0x64, 0xf4, 0xc0, 0x1e, 0xc3, 0x68, 0x89, 0x5d, 0x93, 0x6b, 0x3e,
	0x20, 0xf9, 0x48, 0x2c, 0x86, 0xf1, 0x27, 0x95, 0xaf, 0x8b, 0x4a, 0xdf, 0xdd, 0x7d, 0x78, 0xcb,
	0x87, 0x64, 0xfe, 0x2b, 0xb1, 0xa7, 0x70, 0xaf, 0x3f, 0xc4, 0xf2, 0x11, 0x2d, 0x33, 0x76, 0xcb,
	0x64, 0xca, 0x48, 0xe7, 0x25, 0x02, 0xa6, 0xcb, 0xd2, 0x0a, 0x34, 0x9f, 0x55, 0xfe, 0x43, 0x19,
	0x7d, 0xf8, 0xe0, 0x37, 0xd5, 0x2a, 0xba, 0x7b, 0x22, 0x29, 0x66, 0xcf, 0xe0, 0xaa, 0xab, 0x72,
	0xdc, 0xd4, 0x8d, 0xb6, 0xf6, 0xab, 0x2d, 0x76, 0x9a, 0xd6, 0x1f, 0xca, 0xfb, 0x67, 0x79, 0x59,
	0xec, 0x74, 0xb2, 0x80, 0x87, 0x17, 0xdd, 0x44, 0x61, 0x5b, 0x96, 0x42, 0x58, 0xf7, 0xe8, 0xfe,
	0xc2, 0x68, 0x95, 0x8b, 0x4c, 0x79, 0xca, 0x49, 0x5e, 0xc3, 0xc4, 0xfd, 0x93, 0xea, 0x6f, 0x20,
	0x72, 0xec, 0x1a, 0x4c, 0xdd, 0x2d, 0xa4, 0xca, 0xb3, 0xff, 0x66, 0xf2, 0x6b, 0x3f, 0xf3, 0x7e,
	0xef, 0x67, 0xde, 0x9f, 0xfd, 0xcc, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x99, 0x1a, 0x1c, 0x23,
	0x8b, 0x02, 0x00, 0x00,
}
